---
- name: Install addons
  hosts: all
  gather_facts: yes
  vars:
    subnet: 172.17.0.0/16
    #https_proxy:
    #addons:
    #  - docker
    #  - git
  environment: "{{ proxy_env | default(omit)}}"
  tasks:
    - name: Install docker-ce
      import_role:
        name: docker
      tags: docker
      when: '"docker" in addons'

    - name: Install git
      package:
        name: git
        state: present
      when: '"git" in addons'
