---
- name: Check host usage
  hosts: all
  gather_facts: no
  tasks:
    - name: Get memory avail
      shell: free -m | grep -i Mem | awk '{print $NF}'
      register: memory_avail
      tags: memory

    - name: Print total memory avail
      debug:
        msg: "{{ memory_avail.stdout | trim | int}}"
      tags: memory

    - name: Get cpu load usage 15mins
      shell: uptime  | awk '{print $NF}'
      register: cpu_load
      tags: cpu

    - name: Print cpu load usage
      debug:
        msg: "{{ cpu_load.stdout | trim }}"
      tags: cpu

    - name: Get virt vol disk usage
      shell: df -m --output=ipcent /var/lib/libvirt/images/  | tail -1
      register: disk_usage
      tags: disk

    - name: Print virt vol disk usage
      debug:
        msg: "{{ disk_usage.stdout | trim }}"
      tags: disk
