---
- name: Set iptables dnat rules
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: DNAT configuration
      iptables:
        table: nat
        chain: PREROUTING
        jump: DNAT
        protocol: "{{ item.protocol}}"
        destination_port: "{{ item.dport}}"
        to_destination: "{{ item.destination }}"
        state: "{{ item.state }}"
        comment: "cloudLab DNAT"
        wait: 20
      loop: "{{ rules }}"

